name: Build and test with venv

on:
  pull_request:

  workflow_dispatch:

jobs:
  pip-build:
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - ubuntu-22.04
        - macos-latest
        python-version:
        - '3.13'
  
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Create virtual environment
        run: |
          python -m venv env

      - name: Install xmipp4-core
        run: |
          env/bin/pip install git+https://github.com/gigabit-clowns/xmipp4-core@main -vvv

      - name: Install with pip
        run: env/bin/pip install . -vvv

      - name: Show library version from Python
        run: |
          env/bin/python -c "import xmipp4; print(xmipp4.__version__)"
