name: Build and test with pip

on:
  pull_request:

  workflow_dispatch:

jobs:
  pip-build:
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - ubuntu-22.04
        - macos-latest
        - windows-latest
        python:
        - 3.10
  
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install xmipp4-core
        run: |
          pip install git+https://github.com/gigabit-clowns/xmipp4-core@main -vvv

      - name: Install with pip
        run: pip install . -vvv

      - name: Show library version from Python
        run: |
          python -c "import xmipp4; print(xmipp4.__version__)"
